main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('display', views.display_matkul, name='display'),
    path('detail/<str:mata_kuliah>', views.detail_matkul, name='detail'),
    path('del_matkul/<str:mata_kuliah>', views.del_matkul, name='del_matkul')
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Kuliah(models.Model):
    mata_kuliah = models.CharField(max_length = 200)
    dosen = models.CharField(max_length = 200)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    semester = models.CharField(max_length = 200)
    ruang_kelas = models.CharField(max_length = 200)

main/forms.py
from django import forms
from .models import Kuliah
from django.forms import ModelForm

##Create your forms here

class KuliahForm(ModelForm):
    class Meta:
        model = Kuliah
        fields = '__all__'
        

main/views.py
from django.shortcuts import render,redirect
from .forms import KuliahForm
from .models import Kuliah


def home(request):
    if request.method == "POST":
        form = KuliahForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:home')
    else:
        form = KuliahForm
    context = {'form' : form}
    return render(request, 'main/home.html', context)

def display_matkul(request):

    isi = Kuliah.objects.all()
    return render(request, 'main/displayMatkul.html', {'isi' : isi})

def del_matkul(request, mata_kuliah):
    isi = Kuliah.objects.filter(mata_kuliah = mata_kuliah)
    isi.delete()
    return redirect('main:home')

def detail_matkul(request, mata_kuliah):
    isi = Kuliah.objects.filter(mata_kuliah = mata_kuliah)
    return render(request, 'main/detailMatkul.html', {'isi' : isi})

main/templates/main/detailMatkul.html
{% extends 'base.html' %}

{% block meta %}
<title>Detail Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>Detail Mata Kuliah</h2>
        </div>
    </div>

    <div class="row">
        <table class="table table-borderless">
            {% for info in isi %}
            <tr>
                <th>Mata Kuliah</th>
                <td>{{info.mata_kuliah}}</td>
            </tr>
            <tr>
                <th>Dosen Pengajar</th>
                <td>{{info.dosen}}</td>
            <tr>
                <th>Jumlah SKS</th>
                <td>{{info.jumlah_sks}}</td>
            </tr>
            <tr>
                <th>Deskripsi</th>
                <td>{{info.deskripsi}}</td>
            </tr>
            <tr>
                <th>Semester</th>
                <td>{{info.semester}}</td>
            </tr>
            <tr>
                <th>Ruang Kelas</th>
                <td>{{info.ruang_kelas}}</td>
            </tr>
             
        </table>
    </div>
    <div class="row">
        <div class="col text-center">
            <form>
                <button type="submit" class="btn btn-outline-danger btn-block" formaction="{% url 'main:del_matkul' info.mata_kuliah %}">Delete</button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

main/templates/main/displayMatkul.html
{% extends 'base.html' %}

{% block meta %}
<title>List Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>List Mata Kuliah</h2>
        </div>
    </div>

    <div class="row">
        <table class="table table-borderless">
            <tr>
                <th>Mata Kuliah</th>
                <th>Dosen</th>
            </tr>
            {% for info in isi %}
            <tr>
                <td>{{info.mata_kuliah}}</td>
                <td>{{info.dosen}}</td>
                <td>
                    <form>
                        <button type="submit" class="btn btn-outline-info" formaction="{% url 'main:detail' info.mata_kuliah %}">Detail</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{$ load static %}
{% block meta %}
    <title>Mata Kuliah</title>
{% endblock meta %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>Mata Kuliah</h2>
        </div>
    </div>

    <div class="row">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
    
    
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

 <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>
  <body class="mt-5">

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="display">Display</a>
        </div>
      </div>
    </nav>

    <!-- <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="display">Display</a>
          </div>
        </div>
        </div>
      </nav> -->
      {% block content %}
      {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>